project_id = "hujuqkhbdptsdnbnkslo"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.send-download-email]
verify_jwt = false

[functions.send-whatsapp-download]
verify_jwt = false

[functions.download-file]
verify_jwt = false